import pytest
import pandas as pd
import numpy as np
from unittest.mock import Mock

@pytest.fixture
def grab_test_X_additional_feats():
    data_dict = {
        "FFT answer": {
            "Q1": "Nurses were great",
            "Q2": "Communication was fantastic",
            "Q3": "Impossible to find parking, but pleased to get an appointment close to home",
            "Q4": "Food and drink selection very limited",
            "Q5": "The ward was boiling hot, although staff were great at explaining details",
        },
        "FFT_q_standardised": {
            "Q1": "what_good",
            "Q2": "what_good",
            "Q3": "could_improve",
            "Q4": "could_improve",
            "Q5": "could_improve",
        },
    }
    text_X_additional_feats = pd.DataFrame(data_dict)
    text_X_additional_feats.index.name = 'Comment ID'
    return text_X_additional_feats


@pytest.fixture
def mock_read_csv(mocker, test_raw_data):
    mock = Mock()
    mocker.patch('pandas.read_csv', return_value=test_raw_data)
    return mock


@pytest.fixture
def test_raw_data():
    data_dict = {
        "Comment ID": {
            0: "Q1",
            1: "Q2",
            2: "Q3",
            3: "Q4",
            4: "Q5",
            5: "Q6",
            6: "Q7",
            7: "Q8",
            8: "Q9",
            9: "Q10",
        },
        "Trust": {
            0: "Trust A",
            1: "Trust A",
            2: "Trust A",
            3: "Trust A",
            4: "Trust A",
            5: "Trust A",
            6: "Trust A",
            7: "Trust A",
            8: "Trust A",
            9: "Trust A",
        },
        "Respondent ID": {
            0: "Anon",
            1: "Anon",
            2: "Anon",
            3: "Anon",
            4: "Anon",
            5: "Anon",
            6: "Anon",
            7: "Anon",
            8: "Anon",
            9: "Anon",
        },
        "Date": {
            0: "30/09/2021",
            1: "30/09/2021",
            2: "30/09/2021",
            3: "30/09/2021",
            4: "30/09/2021",
            5: "30/09/2021",
            6: "30/09/2021",
            7: "30/09/2021",
            8: "30/09/2021",
            9: "30/09/2021",
        },
        "Service type 1": {
            0: "Department A",
            1: "Department A",
            2: "Department A",
            3: "Department A",
            4: "Department A",
            5: "Department A",
            6: "Department A",
            7: "Department A",
            8: "Department A",
            9: "Department A",
        },
        "Service type 2": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "FFT categorical answer": {
            0: 1,
            1: 1,
            2: 1,
            3: 1,
            4: 2,
            5: 1,
            6: 1,
            7: 1,
            8: 2,
            9: 2,
        },
        "FFT question": {
            0: "FFT Why?",
            1: "FFT Why?",
            2: "FFT Why?",
            3: "FFT Why?",
            4: "FFT Why?",
            5: "FFT Why?",
            6: "FFT Why?",
            7: "FFT Why?",
            8: "FFT Why?",
            9: "FFT Why?",
        },
        "FFT answer": {
            0: "Did not answer",
            1: "Nothing.",
            2: "Did not answer",
            3: "None.",
            4: "Cue waiting time by an hour.",
            5: "Did not answer",
            6: "None. Quite satisfied.",
            7: "Cut the waiting time from 2 hours before appointment to 1 hour depending which hospital.",
            8: "Nothing at all.",
            9: "Nothing.",
        },
        "Person identifiable info?": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Comment sentiment": {
            0: np.NaN,
            1: 1.0,
            2: np.NaN,
            3: 1.0,
            4: 3.0,
            5: np.NaN,
            6: 2.0,
            7: 3.0,
            8: 1.0,
            9: 1.0,
        },
        "Gratitude/ good experience": {
            0: np.NaN,
            1: 1.0,
            2: np.NaN,
            3: 1.0,
            4: np.NaN,
            5: np.NaN,
            6: 1.0,
            7: np.NaN,
            8: 1.0,
            9: 1.0,
        },
        "Negative experience": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Not assigned": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Organisation & efficiency": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Funding & use of financial resources": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Non-specific praise for staff": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Non-specific dissatisfaction with staff": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Staff manner & personal attributes": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Number & deployment of staff": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Staff responsiveness": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Staff continuity": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Competence & training": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Unspecified communication": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Staff listening, understanding & involving patients": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Information directly from staff during care": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Information provision & guidance": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Being kept informed, clarity & consistency of information": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Service involvement with family/ carers": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Patient contact with family/ carers": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Contacting services": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Appointment arrangements": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: 1.0,
            8: np.NaN,
            9: np.NaN,
        },
        "Appointment method": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Timeliness of care": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: 1.0,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Pain management": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Diagnosis & triage": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Referals & continuity of care": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Length of stay/ duration of care": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Discharge": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Care plans": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Patient records": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Links with non-NHS organisations": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Cleanliness, tidiness & infection control": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Safety & security": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Provision of medical equipment": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Service location": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Transport to/ from services": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Parking": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Electronic entertainment": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Feeling safe": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Patient appearance & grooming": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Mental Health Act": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Equality, Diversity & Inclusion": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Admission": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Collecting patients feedback": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Column to outline any additional comment content which doesn't map to a topic.": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Safeguarding concerns?": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Labelling not possible": {
            0: 1.0,
            1: 0.0,
            2: 1.0,
            3: 0.0,
            4: 0.0,
            5: 1.0,
            6: 0.0,
            7: 0.0,
            8: 0.0,
            9: 0.0,
        },
        "Environment & Facilities": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Supplying & understanding medication": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Activities & access to fresh air": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Food & drink provision & facilities": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Sensory experience": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Impact of treatment/ care": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Psychological therapy arrangements": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Existence of services": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Choice of services": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Out of hours support (community services)": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
        "Learning organisation": {
            0: np.NaN,
            1: np.NaN,
            2: np.NaN,
            3: np.NaN,
            4: np.NaN,
            5: np.NaN,
            6: np.NaN,
            7: np.NaN,
            8: np.NaN,
            9: np.NaN,
        },
    }
    data = pd.DataFrame(data_dict)
    return data
